version: '3.8'

services:
  django-web:
    build: .
    container_name: django-docker
    command: gunicorn --bind 0.0.0.0:8000 OnlineShop.wsgi:application
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
