# Generated by Django 5.2 on 2025-04-18 11:15

import datetime
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('laptop', 'Laptop'), ('smartphone', 'Smartphone')], max_length=20, unique=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('screen_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('screen_resolution', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Формат має бути як 1920x1080', regex='^\\d{3,4}x\\d{3,4}$')])),
                ('screen_ref_rate', models.IntegerField(default=60)),
                ('sim_quantity', models.IntegerField(default=1)),
                ('network_generations', models.CharField(max_length=20)),
                ('cpu_model', models.CharField(max_length=15)),
                ('cpu_cores_num', models.IntegerField(default=8)),
                ('ram', models.IntegerField(default=4)),
                ('storage', models.IntegerField(default=120)),
                ('main_camera', models.CharField(max_length=30)),
                ('max_video_resolution', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Формат має бути як "7680 x 4320" або "7680 x 4320 8K UHD"', regex='^\\d{3,5}\\sx\\s\\d{3,5}(?:\\s[\\w\\s]{2,15})?$')])),
                ('frontal_camera', models.CharField(max_length=30)),
                ('nfc', models.BooleanField(default=False)),
                ('connector_type', models.CharField(max_length=10)),
                ('battery', models.IntegerField(default=2000)),
                ('weight', models.IntegerField(default=200)),
            ],
            options={
                'db_table': 'smartphones',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('seller', 'Seller')], default='user', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('screen_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scree_resolution', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Формат має бути як 1920x1080', regex='^\\d{3,4}x\\d{3,4}$')])),
                ('screen_ref_rate', models.IntegerField(default=60)),
                ('cpu_model', models.CharField(max_length=15)),
                ('cpu_cores_num', models.IntegerField(default=4)),
                ('cpu_frequency', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ram', models.IntegerField(default=4)),
                ('ram_type', models.CharField(max_length=5)),
                ('storage', models.IntegerField(default=120)),
                ('storage_type', models.CharField(max_length=5)),
                ('gpu_model', models.CharField(max_length=15)),
                ('cpu_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpu_brand', to='myapp.brand')),
                ('gpu_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpu_brand', to='myapp.brand')),
            ],
            options={
                'db_table': 'laptops',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=False)),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('category_prod_id', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
    ]
